### ISSUE TITLE
Crashing on android 11 on start recording

### ISSUE THREAD

**Issue by roitnaidu23** [Isvisoft/flutter_screen_recording#62]
`Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION`

D/AndroidRuntime( 4061): Shutting down VM
E/AndroidRuntime( 4061): FATAL EXCEPTION: main
E/AndroidRuntime( 4061): Process: com.userqual.app, PID: 4061
E/AndroidRuntime( 4061): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.userqual.app/com.userqual.app.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 4061): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
E/AndroidRuntime( 4061): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
E/AndroidRuntime( 4061): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 4061): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4061): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 4061): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 4061): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4061): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 4061): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 4061): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4061): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 4061): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 4061): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 4061): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/AndroidRuntime( 4061): 	at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime( 4061): 	at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime( 4061): 	at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime( 4061): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 4061): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
E/AndroidRuntime( 4061): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
E/AndroidRuntime( 4061): 	at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:66)
E/AndroidRuntime( 4061): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 4061): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 4061): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime( 4061): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime( 4061): 	at android.app.Activity.dispatchActivityResult(Activity.java:8310)
E/AndroidRuntime( 4061): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
E/AndroidRuntime( 4061): 	... 11 more
E/AndroidRuntime( 4061): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 4061): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:479)
E/AndroidRuntime( 4061): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 4061): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/AndroidRuntime( 4061): 	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by roitnaidu23** [comment]
I have added `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in AndroidManifest.xml

**Comment by jtmuller5** [comment]
Taken from this [answer on SO](https://stackoverflow.com/a/61277020/12806961):

Add android:foregroundServiceType="mediaProjection" to the <service> element in the manifest for your service.

**Comment by Just-Ali** [comment]
@roitnaidu23 You should add this line "<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>" inside the "application" tag in AndroidManifest.xml file.

You can take a look here https://www.gitmemory.com/issue/Isvisoft/flutter_screen_recording/44/712675784

**Comment by Just-Ali** [comment]
@roitnaidu23 You should add this line:
"<service android:name="changjoopark.com.flutter_foreground_plugin.FlutterForegroundService" android:foregroundServiceType="mediaProjection"/>"
inside the "application" tag in AndroidManifest.xml file.

You can take a look here https://www.gitmemory.com/issue/Isvisoft/flutter_screen_recording/44/712675784

If this solution doesn't work for you please let me know

**Comment by Just-Ali** [comment]
@ roitnaidu23 You must add this line:
`<service android:name=" changjoopark.com.flutter_foreground_plugin.FlutterForegroundService " android:foregroundServiceType=" mediaProjection "/>`
inside the "application" tag in the AndroidManifest.xml file.

I found this solution here https://www.gitmemory.com/issue/Isvisoft/flutter_screen_recording/44/712675784

If this solution doesn't work for you please let me know

**Comment by Lix-ai** [comment]
Hi It didn't work for me I don't know which android I use (this the emulator?)

But I have the same issue:


Hi,
It crash on Record Screen and Record audio always fail with :
"
I/System.out( 2065): Error onMethodCall startRecordScreen
I/System.out( 2065): null
"




See all log for both trying
"
I/flutter ( 2065): Foreground on Started
E/MediaRecorder( 2065): setAudioSource called in an invalid state(4)
I/System.out( 2065): Error onMethodCall startRecordScreen
I/System.out( 2065): null
I/flutter ( 2065): Foreground on Started
I/System.out( 2065): 1280 720
I/System.out( 2065): file --- /storage/emulated/0/DCIM/Title.mp4
D/AndroidRuntime( 2065): Shutting down VM
E/AndroidRuntime( 2065): FATAL EXCEPTION: main
E/AndroidRuntime( 2065): Process: com.example.flutterthe_a_app, PID: 2065
E/AndroidRuntime( 2065): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.example.flutterthe_a_app/com.example.flutterthe_a_app.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 2065): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
E/AndroidRuntime( 2065): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
E/AndroidRuntime( 2065): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 2065): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 2065): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 2065): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime( 2065): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2065): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 2065): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 2065): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2065): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 2065): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 2065): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 2065): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
E/AndroidRuntime( 2065): 	at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime( 2065): 	at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime( 2065): 	at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime( 2065): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 2065): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
E/AndroidRuntime( 2065): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
E/AndroidRuntime( 2065): 	at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:66)
E/AndroidRuntime( 2065): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 2065): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 2065): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:625)
E/AndroidRuntime( 2065): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:583)
E/AndroidRuntime( 2065): 	at android.app.Activity.dispatchActivityResult(Activity.java:8305)
E/AndroidRuntime( 2065): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
E/AndroidRuntime( 2065): 	... 11 more
E/AndroidRuntime( 2065): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 2065): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:479)
E/AndroidRuntime( 2065): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 2065): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
E/AndroidRuntime( 2065): 	at android.os.Binder.execTransact(Binder.java:1123)
E/AndroidRuntime( 2065): 
I/Process ( 2065): Sending signal. PID: 2065 SIG: 9
Lost connection to device.
"


I did all the things you required, and have to use 0.4.0 (old foreground service) version as your dependencies request.

Thanks in advance :)!

**Comment by utkarshshendge** [comment]
@Lix-ai did you find a solution?

**Comment by deepak-ariceum** [comment]
It's still not working after doing what all the issues suggest. Please fix this, as this is an important library many use. Thank you!
This is the error I'm getting.

```
I/MediaRecorderJNI( 6839): prepare
E/MediaRecorder( 6839): prepare failed: -2147483648
D/--INIT-RECORDER( 6839): prepare failed.
I/System.out( 6839): Error startRecordScreen
I/System.out( 6839): prepare failed.
D/ViewRootImpl@a19b914[MainActivity]( 6839): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 6839): prepareNavigationBarInfo() DecorView@eb2e75a[MainActivity]
D/InputMethodManager( 6839): getNavigationBarColor() -855310
D/InputTransport( 6839): Input channel destroyed: 'ClientS', fd=85
D/AndroidRuntime( 6839): Shutting down VM
E/AndroidRuntime( 6839): FATAL EXCEPTION: main
E/AndroidRuntime( 6839): Process: com.example.tiktok_clone_6, PID: 6839
E/AndroidRuntime( 6839): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=333, result=-1, data=Intent { (has extras) }} to activity {com.example.tiktok_clone_6/com.example.tiktok_clone_6.MainActivity}: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 6839):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
E/AndroidRuntime( 6839):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
E/AndroidRuntime( 6839):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 6839):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6839):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6839):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/AndroidRuntime( 6839):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 6839):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 6839):        at android.app.ActivityThread.main(ActivityThread.java:7807)
E/AndroidRuntime( 6839):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6839):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6839):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/AndroidRuntime( 6839): Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 6839):        at android.os.Parcel.createException(Parcel.java:2088)
E/AndroidRuntime( 6839):        at android.os.Parcel.readException(Parcel.java:2056)
E/AndroidRuntime( 6839):        at android.os.Parcel.readException(Parcel.java:2004)
E/AndroidRuntime( 6839):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime( 6839):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:68)
E/AndroidRuntime( 6839):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:147)
E/AndroidRuntime( 6839):        at com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.onActivityResult(FlutterScreenRecordingPlugin.kt:63)
E/AndroidRuntime( 6839):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 6839):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 6839):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:802)
E/AndroidRuntime( 6839):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 6839):        at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime( 6839):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
E/AndroidRuntime( 6839):        ... 11 more
E/AndroidRuntime( 6839): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 6839):        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:501)
E/AndroidRuntime( 6839):        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime( 6839):        at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime( 6839):        at android.os.Binder.execTransact(Binder.java:994)
E/AndroidRuntime( 6839): 

```

**Comment by salime45** [comment]
Fix
