### ISSUE TITLE
Problem occured when running pub get with latest stable version of flutter 3.10.5

### ISSUE THREAD

**Issue by dernoun** [Isvisoft/flutter_screen_recording#88]
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.

**Comment by Angel1404** [comment]
Tengo el mismo problema.

**Comment by AbuMuftee** [comment]
@dernoun and lower version of kotlin. Can I work on this problem for the upgrade

**Comment by wantroba** [comment]
Same problem here

**Comment by 7ANV1R** [comment]
Same warning: 
The plugin `flutter_screen_recording` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
